### ISSUE TITLE
pa_2018.shp and pa_2020.shp have extraneous VTDs without any votes

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/pdv-pa#3]
(Since models are being built from VEST's shapefiles and being derived from its processed data, both VEST's processed data and geometry should be independently validated.  If any errors are found through validation, then they can be corrected before being unwittingly propagated further.  However, this repo is just replicating VEST's processing steps rather than validating VEST's shapefiles against what's expected to be correct.)

VEST's shapefiles have extraneous VTDs in [2018](https://dataverse.harvard.edu/file.xhtml?fileId=5595321&version=59.0) and [2020](https://dataverse.harvard.edu/file.xhtml?fileId=5595329&version=35.0).  These extraneous VTDs didn't have any votes and are listed below.  Compared to the respective county's number of precincts, the counties with an extraneous VTD totaled one more VTD.  For example, Erie County's official results had 149 precincts in both [2018](https://eriecountypa.gov/wp-content/uploads/2019/08/election-master-compiled-2018-general.xls) and [2020](https://eriecountypa.gov/wp-content/uploads/2020/11/Precinct-results-2020-General-Election.xlsx).

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

COUNTYFP | VTDST | NAME
-- | -- | --
011 | 1578P1 | ADAMSTOWN
049 | 999999 | LAKE ERIE

</body>

</html>

**Comment by peter-redistricting-data-hub** [comment]
I'm not sure what you'd like us to do or think is appropriate here. These VTDs are added to "fill out" a state map

**Comment by rootsmusic** [comment]
Ok @peter-redistricting-data-hub, I incorrectly thought that these were VEST's mistakes.
